### ISSUE TITLE
[EPIC] Implement assessment tool annotation process

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#137]
Users should be able to annotate assessment tools as easily as they can tell us about the location and format of age, sex, and diagnosis information. To do so, a user wants to

- [x] I can create a new tool and assign columns to it (#118)
- [x] #138
- [x] I can provide a name for a tool group (#118, #153)
- [ ] I can declare missing values for every column in a tool group (#131)
- [ ] #139
- [ ] #140
