### ISSUE TITLE
Refactor annot-columns for new store

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#248]
The `annot-columns` component needs to be refactored to prepare for our big store refactor. 

## Use cases - I/O

- [x] Display columns mapped to the current category: while I am annotating a specific category, this component shows me a list of all the columns that have been mapped to this category (in the previous categorization step).
  - input:
    - activeCategory (prop from parent): I need to know what category I am invoked for
    - mappedColumns (or some better name) (getter): the store should return all the columns to me that have been mapped to my `activeCategory`
    - columnDescription (getter): as I am building my visual representation of the columns, I go back and ask the store if there are any descriptions for each column
  - output: none
- [x] Fire a store mutation to remove a column from this category (unlink): if I notice that one of the columns has been linked to my `activeCategory` by accident, then there should be some UI element that allows me to "unlink" this column so that it is no longer linked to my `activeCategory` in the store
  - input: as above
  - output: 
    - unlink / changeCategoryLink (mutation): fire a store mutation for the column that is being unlinked (we might already have something like this that can be reused in #243)

## Internal State

This component doesn't have to keep local state

## Tasks

- [x] Write the component tests to test (at least) the two above functionalities
- [x] Include in the test a mock of the mutation (for documentation, not technically necessary)
- [x] Refactor the component to pass the component tests
- [x] Check that there is no logic leftover inside of the component that we don't need any more

**Comment by surchs** [comment]
> Does removeColumn method in the current implementation in a way do the unlink/changeCategoryLink mutation's job mentioned here?

Very close, but not quite. It emits the fact that a column should be removed / unlinked as an event that a parent component would have to listen to. We instead want to declare this to the store via mutation / action

**Comment by rmanaem** [comment]
So check when the button is clicked a mutation is set off?

**Comment by surchs** [comment]
Yes, that's how I had thought of the second functionality checkbox in the issue description.
