### ISSUE TITLE
create getter for json version of data dictionary

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#268]
I want a store getter that creates a JSON object with all annotations for me, so I can provide it to the user as a downloadable file for saving.

Something like this:
![get_data_dictionary](https://user-images.githubusercontent.com/1302022/232563147-7f8aed56-cf73-43fb-8087-abb17bcf99a6.jpg)

We need:

- [x] #406
- [x] #407
- [x] #408
  - columns should follow same order as in supplied .tsv

Then the "meta getter" should 
- iteratively step through each column in the data dictionary and 
- rely on the above getters to create a JSON object for the respective column to
- create a schema-valid representation of the annotations of this one column and
- finally combine all of the individual columns into one big JSON object and
- return this JSON object

The schema is valid for BIDS and BIDS+Neurobagel outputs. Schema validation is optional for now.
[Example output file](https://github.com/neurobagel/bagel-cli/blob/8e512fa14e1db99f3e8fd378cb2a4c5e721d5e32/bagel/tests/data/example2.json)

Other requirements:

- [ ] depending components have been checked and are calling this mutation correctly
- [ ] have unit tests to check functionality
- [ ] needed store state variables exist already or have been created if not

**Comment by jarmoza** [comment]
@surchs We should discuss the new, outputted json format of the data dictionary here.

**Comment by surchs** [comment]
Aha, yes, good point! We currently [have a draft schema](https://github.com/neurobagel/bagelbids/blob/main/bagelbids/dictionary_models.py) for this in the works in the CLI repo. Here would be a (very simplistic) example instance of it: https://github.com/neurobagel/bagelbids/blob/main/bagelbids/tests/data/example2.json

The schema we've written so far is built to be valid for both a BIDS data dictionary and a Neurobagel enhanced data dictionary. We can serialize the pydantic model into a jsonschema and you could then use the jsonschema inside the annotator to validate both the user provided data dictionary (during input), and also the created output data dictionary (if that makes sense).

**Comment by surchs** [comment]
Hey folks, I'll pick this back up now.

**Comment by surchs** [comment]
One question here is: if the user has mapped a column to a category, but then not finished annotating this column (partially or at all), should we still create it in the output?

**Comment by surchs** [comment]
Another issue I just encountered: we have added controlled term identifiers to the discrete choices for categories like "Sex", but we'll probably have to do the same thing for the transform heuristics. An intermediate fix might be to just put the shorthand namespaced format as the label we also show the user. As in:

`"euro"` -> `"bg:euro"`

**Comment by surchs** [comment]
OK, based on our brief conversation, we'll split this issue up into sub-issues for:

a getter that gives me:
- a well formatted annotated "continuous" column
- a well formatted annotated "discrete" column
- a knitted together version of "continuous" and "discrete" and also un-annotated columns that is schema compliant
- (maybe) a getter that tells me for a given column whether it is "continuous", "discrete", or "unannotated"

**Comment by surchs** [comment]
I think we can close this now

**Comment by jarmoza** [comment]
Closed by #431
