### ISSUE TITLE
Best way to create unit tests re: mocking store

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#295]
## Older context

The question has come up in #291 as to the best (or most proper/uniform) way to mock the store for our unit tests.

Presently we are creating a `state` object in the test script file which getters and mutations can access. However, to properly mock the store for something more complex like actions, @surchs has suggested that we may want to uniformly define a `store` object inside of which will be things like getters and mutations.

The alternate is to mock the store by initializing the an instance of the real Vuex store itself and utilizing that.

## Context
This problem is not unique to unit-tests but applies to all tests that do not test the complete app at runtime (i.e. are not e2e tests) and involve getters. The problem here is that in the store and when run in unit-tests, getters are curried, i.e. they return functions themselves. But at runtime the same getters behave like actual functions. So we have this problem that calling getters like we would call them inside of a component would fail

### Mocking the getters to simply return the expected result
https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/component/annot-columns.cy.js#L6-L17

Adding the (ignored) argument name in the mock for better readability and compatibility with the invoking component

### Being extra clever and un-currying (?) the getters in the test
https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/unit/store-getter-getUniqueValues.cy.js#L36-L43

and with a different flavour:
https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/unit/store-getter-isPageAccessible.cy.js#L4

This looks smart but becomes unwieldy quickly for getters that have deep dependencies on other getters because their shared reliance on the state makes it necessary to almost create the entire runtime state just to mock a single getter. So overall, probably not a good idea.

## Tasks
- [ ] discuss which of these options for getter mocking in our (non e2e) tests we prefer
- [ ] also pay attention to maintainability vs readability (i.e. how much does brain hurt when reading vs when API changes)
- [ ] document the choice
- [ ] make a note to refactor existing tests to use this form whenever they go through PR review

**Comment by surchs** [comment]
@rmanaem can you take a look and see if there are other forms of using and mocking getters or their inputs that we'd like to standardize?

**Comment by rmanaem** [comment]
I found this in `getJSONOutput` unit test for getters that utilize other getters:
https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/unit/store-getter-getJsonOutput.cy.js#L53-L80

**Comment by rmanaem** [comment]
Something else that came to mind for component tests was to mock the getters/mutations in the computed property instead of in state mock them, I wonder if that is better practice as that's how the component utilizes the getters/mutations.

**Comment by surchs** [comment]
I think that's not optional, no? Do you have an example where we feed required getters to the component inside of the mocked  store object?

**Comment by rmanaem** [comment]
> Do you have an example where we feed required getters to the component inside of the mocked store object?

I believe we always do that, no?

**Comment by surchs** [comment]
Not sure if we mean the same thing, but I think we **always** give the component its getters as a computed thing, e.g. here: 

https://github.com/neurobagel/annotation_tool/blob/d4be4f28c1c56268796b1de72c0603d1d009029d/cypress/component/annot-categorical.cy.js#L65-L73

Do you have any example where we do not do that but provide them only as wrapped inside the store?

**Comment by rmanaem** [comment]
Yea you're right, I forgot we do that when mounting the component. 😅

**Comment by surchs** [comment]
For reviewer, I added a note here: https://github.com/neurobagel/documentation/wiki/Cypress-Test-Snippets#pass-a-vuex-getter-that-takes-an-argument-or-simulating-a-mapgetters-field

**Comment by rmanaem** [comment]
Thanks for taking care of this @surchs!
I noticed a small typo in the 2nd reason `Getters can*` but other than its good to go.
