### ISSUE TITLE
Annotation Page Refactor for Phase 2 Store Refactor

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#347]
Now that we are into the [second phase of the store refactor](https://github.com/neurobagel/annotation_tool/issues/305) - moving onto the annotation and download pages - it will be necessary to refactor the annotation page itself before its dependent components can be fully tested manually and via our page-level e2e tests for the page.

Below is a list of the refactor work that needs to be done to the annotation page:

- [x] Tabs now must look at new store configuration for info on their construction (previously in store field `annotationDetails`) #348 
- [x] Column unlinking from categories must be updated - includes a) transforming a column to its original unannotated state and b) the actual unlinking of a column from its previously assigned category #376 
- [x] Removing all old tool group functionality
- [x] Altering how missing values are added and removed to accord with the store refactor #381 
- [x] Altering how the annotations are 'saved' now that changes are being made to `dataDictionary.annotated` instead of the previous `dataTable.annotated`

Once this work is complete, then the e2e test for the annotation can be [re-enabled for the github testing workflow](https://github.com/neurobagel/annotation_tool/issues/341). At this point, the e2e tests for the annotation page will likely need to be updated as well:

- [x] Re-enable annotation page e2e test (See #341.)
- [x] Update annotation page e2e test until all tests pass

**Comment by jarmoza** [comment]
In light of the possible complexity of this page refactor, I will spin off this work into several PRs.

**Comment by jarmoza** [comment]
Blocked by #386

**Comment by surchs** [comment]
This seems to be unblocked / finished. @jarmoza / @rmanaem could you check + close?

**Comment by rmanaem** [comment]
I believe this is finished @jarmoza could you confirm?

**Comment by jarmoza** [comment]
@surchs / @rmanaem Confirmed. Closed.
