### ISSUE TITLE
meta getter to step through each column and iteratively build the JSON object

### ISSUE THREAD

**Issue by surchs** [neurobagel/annotation_tool#408]
A getter to create the ready-for-download JSON object of all annotations

Then the "meta getter" should

- [x] iteratively step through each column in the data dictionary and
- [x] getter to determine whether a column has been categorized  -> no getter, just logic
- [x] getter to determine whether a column has been categorized as "discrete" or "continuous" (and in the future even "assessment tool")
- [x] rely on the category specific getters to create a JSON object for the respective column to
- [x] create a schema-valid representation of the annotations of this one column and
- [x] finally combine all of the individual columns into one big JSON object and
- [x] return this JSON object
- [x] unannotated information in the user provided data dictionary or from the data dictionary skeleton should also be included
- [x] the output format should be valid according to the data dictionary schema

**Comment by surchs** [comment]
Depends on #407 and #406

**Comment by jarmoza** [comment]
Taking over on this issue.
